### ISSUE TITLE
Sequel::Snowflake::Dataset#fetch aborts abruptly

### ISSUE THREAD

**Issue by MPT-ladams** [vendasta/sequel-snowflake#16]
Using Ruby 2.7.2 (also tried 3.2.1 & 3.2.2) with the latest Snowflake ODBC driver (3.1.3) on Mac OS X Sonoma 14.0. Using the latest sequel-snowflake version (also tried 2.0.0).

ODBC driver connection working properly per docs using iodbctest (https://docs.snowflake.com/developer-guide/odbc/odbc).

When running the following in a Ruby console, this aborts the console abruptly. No exceptions thrown. Few lines in the logs I've found below.

```
db = Sequel.connect(adapter: :snowflake, drvconnect: connection_str)
db.fetch("select current_version();").all
```

Connection string:
```
"driver=/opt/snowflake/snowflakeodbc/lib/universal/libSnowflake.dylib;LogLevel=5;server=server.snowflakecomputing.com;uid=username;pwd=password"
```

Notable lines from logs...

snowflake_odbc_connection.log:
```
2023-11-15T16:53:45.441 ERROR 4527 Simba::ODBC::Statement::SQLFetchScroll: [Snowflake][ODBC] (10480) Fetch type not supported, as fetch orientation is not compatible with current settings.
```

snowflake_odbc_generic.log:
```
2023-11-15T16:53:45.294 INFO  4527 Simba::Snowflake::SFDriver::appendLatestVersion: Your driver version (3.1.3) is different from the latest driver version supported by Snowflake (2.21.1)
```

Any idea on solution or further debugging? Thanks in advance!

**Comment by ccoffey** [comment]
@MPT-ladams I think I am having the same issue that you reported. I found this after I created https://github.com/jeremyevans/sequel/issues/2114

I tried downgrading to `2.3.11` (as you suggested) but it did not work for me.

Here is what I did:

I think brew is telling me that I have two versions installed (`2.3.11` & `2.3.12`)
```
brew info unixodbc
==> unixodbc: stable 2.3.12 (bottled)
ODBC 3 connectivity for UNIX
https://www.unixodbc.org/
Conflicts with:
  virtuoso (because both install `isql` binaries)
/opt/homebrew/Cellar/unixodbc/2.3.11 (48 files, 2.3MB)
  Poured from bottle using the formulae.brew.sh API on 2023-05-19 at 14:25:23
/opt/homebrew/Cellar/unixodbc/2.3.12 (47 files, 2.3MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-09-04 at 20:10:55
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/u/unixodbc.rb
License: LGPL-2.1-or-later
==> Dependencies
Required: libtool ✔
==> Analytics
install: 23,500 (30 days), 80,744 (90 days), 258,426 (365 days)
install-on-request: 2,683 (30 days), 9,067 (90 days), 28,250 (365 days)
build-error: 6 (30 days)
```

I reinstall `ruby-odbc` with `2.3.11`
```
gem uninstall ruby-odbc
gem install ruby-odbc -- --with-odbc-dir=/opt/homebrew/Cellar/unixodbc/2.3.11
```

But it still crashes when I try to query!

```ruby
db.fetch("select current_version();").all
[1]    14340 abort      rails c
```

Any suggestions?

Also, I cannot find the log files that you mentioned `snowflake_odbc_connection.log` and `snowflake_odbc_generic.log`, what directory can I find these in?

**Comment by MPT-ladams** [comment]
@ccoffey I suspect you're still using unixODBC 2.3.12. I would wipe all installs of unixODBC, iODBC, etc and start clean, if possible.

I don't recall unixODBC 2.3.11 being available on Homebrew when I went through this. So I uninstalled 2.3.12 from Homebrew and installed 2.3.11 from source.

I think this guide is pretty good, just update all references to your unixODBC install:
https://community.snowflake.com/s/article/How-to-create-Snowflake-ODBC-DSN-On-MacOS

Also, make sure you're simba.snowflake.ini settings are correct, most notable for me was the path to libiodbcinst.dylib (which I think was the last piece I plugged in to get everything working correctly):
```
ODBCInstLib=/usr/local/iODBC/lib/libiodbcinst.dylib
```

You can enable logs from this config:
```
ErrorMessagesPath=/opt/snowflake/snowflakeodbc/ErrorMessages
LogLevel=6
```

More config available at https://docs.snowflake.com/en/developer-guide/odbc/odbc-parameters.

I should have documented my steps better. But there was a lot of trial and error until I realized it was the unixODBC version.

Good luck!

**Comment by ccoffey** [comment]
@MPT-ladams thank you so much for your help. I uninstalled `2.3.12` & `2.3.11` from brew and manually re-installed `2.3.11` from source. Then uninstalled and reinstalled the gems. And it worked!

```ruby
db.fetch("select current_version();").all
=> [{:"current_version()"=>"8.0.0"}]
```

So I agree with you, there is definitely a problem with `2.3.12`! Thank you again!

**Comment by ccoffey** [comment]
@MPT-ladams I just thought you would like to know. I reached out to Nick Gorham, the creator of unixODBC and he helped me to build `2.3.12` for macOS correctly.

Here is the important parts of our conversations:

**Nick:** Its likely the problem will be down to the SQLWCHAR definition in ruby being 4 byte, and unixODBC uses 2 bytes. iODBC uses 4 bytes. Its not a bug, its possible to store a unicode character in 2 or 4 bytes, both are correct, but they are different. unixODBC has the option to be built in a way that matches what Ruby has built itself with, its just that the people who built unixODBC for OSX didn't build it that way.

**Me:** But 2.3.11 seems to work despite this "bug". I have gotten the expected response for every query I have executed.

**Nick:** That's because you have not tried to return a error. Try a query that returns a error, "select * from wibble" where wibble is a table that doesn't exist.

**Nick:** You can build your own copy after configuring with CFLAGS=-DSQL_WCHART_CONVERT ./configure. Setting that flag, will make the unixODBC build use 4 byte SQLWCHAR. I have seen this problem before so added that flag to address it.

I decided to test this out. First I uninstalled v2.3.11 from my mac:

Remove v2.3.11:
```
cd ~/Downloads/unixODBC-2.3.11
make uninstall
```

configure v2.3.12 with magic flag and install:
```
cd ~/Downloads/unixODBC-2.3.12
CFLAGS=-DSQL_WCHART_CONVERT ./configure
make
make install
```

Test it out:
```ruby
db = Sequel.connect(adapter: :snowflake, drvconnect: conn_str)
=> #<Sequel::Snowflake::Database: {:adapter=>:snowflake, :drvconnect=>"DRIVER

db.fetch("select 1;").all
=> [{:"1"=>1}]
```

I think the best thing to do in order to stop most people from hitting this would be to submit a PR to Homebrew to update: https://github.com/Homebrew/homebrew-core/blob/906d4aba32a21f1aecb8bb46f181752b423efd02/Formula/u/unixodbc.rb#L36

I was hoping to do this today but didn't find the time

**Comment by kwong-yw** [comment]
👋 just checking in on this thread; I tried looking up some more background around this issue, and I noticed this [Snowflake thread](https://community.snowflake.com/s/question/0D50Z0000876lmNSAQ/mac-os-x-snowflake-odbc-drivers) that noted that in `/opt/snowflake/snowflakeodbc/lib/universal/simba.snowflake.ini` there is a section that reads:

```
## Note that this default DriverManagerEncoding of UTF-32 is for iODBC. unixODBC uses UTF-16 by default.
## If unixODBC was compiled with -DSQL_WCHART_CONVERT, then UTF-32 is the correct value.
## Execute 'odbc_config --cflags' to determine if you need UTF-32 or UTF-16 on unixODBC
DriverManagerEncoding=UTF-32
```

I wonder if switching that to UTF-16 instead would also make things work, without resorting to recompiling unixodbc?

**Comment by MPT-ladams** [comment]
@kwong-yw Thank you for finding that reference to DriverManagerEncoding. Changing that setting did in fact work for me without having to recompile unixODBC w/ the DSQL_WCHART_CONVERT flag (also good find @ccoffey).

I uninstalled unixODBC v2.3.11. I installed v2.3.12 via Brew. Then changed simba.snowflake.ini to DriverManagerEncoding=UTF-16. Everything works nicely!

Cheers!

**Comment by santib** [comment]
thanks @kwong-yw ❤️ this bug was driving me crazy

**Comment by trevorh** [comment]
@kwong-yw Any chance you could add a note about the possible changes needed in simba.snowflake.ini for `DriverManagerEncoding` and `ODBCInstLib` to the readme file?

I think it would really help give more visiblity into this - I couldn't figure out why I was getting the aborted fetch as well when isql was connecting just fine and returning query results. isql helped me pinpoint the `ODBCInstLib` issue but it was this issue that sorted out the UTF-16 change needed for the latest version of unixodbc.
